" key_exchange.pl generate this file.  Don't edit.
if !exists('*AmbsearchAdd') | finish | endif
scriptencoding cp932
call AmbsearchAdd('A', 'ˆŸˆ£ˆ¤ˆ«ˆ¬ˆ³ˆµˆÀˆÃˆÄ‰J‰·‰¿‰ß‰ï‰ö‰üŠJŠ¾ŠÃŠÔŠë‹\‹r‹“‹Å‹óŒZŒŠŒ»ŒãŒëŒúQrz‡ÝŽoŽ‰ŽšŽÓŽåHW[‹¤²ºÅÍãVÂÔÕóô‘N‘e‘€‘ˆ‘Š‘˜‘«’W’g’l’˜’©“V“Œ“–“ª“Ä“ò”M”ñ•\•Ž•¶•¹•Ò•Ó•à–A–O–\–ƒ–¡–¾–Ô–û—L—V—\—]—^—a—g—˜N')
call AmbsearchAdd('B', '‰H‰»‹´gâêUl“Ø“ú”L”k”n”{”|”}”~”ƒ”„”…”†”Ž”’”™”š”›”ž”°”±”²”´”º”»”Â”Å”Ó”Ô”Õ”Ø”õ”ö”÷”ü•@•`•a•b•c•n•q•r•s•Ž••‘•”•§•¨•ª•¶•·•½•Ä•Ê•Ó•Ö•×•Ù•Û•à•å•æ•ç•é•ê•ë•ò–R–S–T–U–V–W–X–Y–Z–[–\–]–^–_–`–a–b–c–d–f–h–l–n–o–p–q–v–}–~–‹–––œ–³–Í–Ï–Ø–Ú')
call AmbsearchAdd('C', 'ˆá‹ßŒ_ŒŒŽUŽ¡Ž¿dk¬Ÿ¾ç’l’m’n’p’r’s’t’u’v’x’z’{’|’~’€’’‚’ƒ’„’…’†’‡’ˆ’‰’Š’‹’Œ’’Ž’’’’“’˜’™’š’›’ ’¡’¢’£’¤’¥’¦’§’©’ª’¬’­’®’¯’°’²’´’µ’·’¸’¹’º’¼’½’¾’¿’À’Á’Â“û•ƒ—Í')
call AmbsearchAdd('D', 'ŠÙ‹lŽÖo‘Â‘Ã‘Ä‘Å‘Ê‘ã‘ä‘å‘æ‘è‘÷‘ø’B’D’E’I’c’d’e’f’g’i’j’k’í“D“`“a“c“d“w“x“y“z“{“­“®“¯“°“±“´“¶“·“¹“º“Å“Æ“Ç“Ü“Ý“à•t•ø–Ù')
call AmbsearchAdd('E', 'ˆÌˆÕ‰c‰e‰f‰h‰i‰j‰p‰q‰r‰s‰t‰u‰v‰w‰x‰y‰z‰{‰~‰€‰ƒ‰„‰‡‰ˆ‰‰‰Š‰Œ‰Ž‰‰“‰”‰–‰ï‰ñŠG‹ÝŒb]Ž}dÎ‘I“¾•`•¿–ð')
call AmbsearchAdd('F', '‰‰ùŠÈŠÜŒÃX~ÄŽDMBGU[kß‘D‘o‘‘‘¾‘Ü“J“~“¥“ñ•M•s•t•v•w•x•z•{•|•}•~••‚•ƒ•„•…•†•ˆ•‰•Š•‹••••—•š•›•œ••ž•Ÿ• •¡•¢•¥•¦•§•ª•¬•­•®•±•²•´•µ•¶•à–[–c–h˜V')
call AmbsearchAdd('G', 'ˆÊ‰º‰Í‰ä‰æ‰è‰ê‰ë‰ì‰ðŠNŠOŠQŠSŠTŠUŠXŠYŠ_ŠwŠxŠyŠzŠƒŠÛŠÜŠÝŠáŠâŠæŠçŠèŠùŠú‹U‹V‹X‹Y‹Z‹[‹\‹]‹^‹`‹c‹s‹t‹{‹‹™‹›‹­‹½‹Â‹Ã‹Å‹Æ‹É‹Ê‹á‹â‹ï‹ð‹ñ‹ô‹ö‹÷ŒQŒRŒSŒ^Œ`Œ|Œ}Œ~Œ€Œ‚ŒƒŒŽŒ™Œ Œ±Œ³Œ´ŒµŒ¶Œ·Œ¸Œ¹ŒºŒ»Œ¾ŒÀŒÜŒÝŒßŒàŒâŒãŒäŒåŒéŒêŒëŒìs„†‡‰‹–Ž™ãéº‘g‘¤•¿•û–ˆ–Ø')
call AmbsearchAdd('H', 'ˆêˆø‰H‰^‰f‰h‰p‰Š‰É‰Ê‰Î‰Ô‰ØŠDŠJŠOŠuŠzŠ°Š±Š»ŠÊŠø‹@‹v‹²‹´‹¿Œ@ŒoŒuŒvŒƒŒ´Œ¸ŒÖŒõLT|œ¶×âŽnŽ{ŽŽ•Ž¡ŽÖŽõEGt‰ÈJZjlnqr}¯°¶ö‘j‘|‘‘’‘–‘ª‘¬‘¼’[’e’p’‹’Œ’£’¤’µ’á’ö“f“Œ“”“™“­“´“Æ“ú“ü”c”e”g”h”j”o”p”q”r”s”t”w”x”y”z”Œ”Ž””‘”’”•”–”—” ”§”¨”ª”«”­”¯”º”»”¼”½”¿”À”Â”Å”Æ”Ç”È”É”Ê”Ë”Ì”Í”Ï”Ð”Ñ”Ú”Û”Ü”Þ”ß”à”á”â”ä”å”æ”ç”è”é”ë”ì”í”ï”ð”ñ”ò•@•C•K•M•P•S•U•W•X•Y•[•\•]•a•i•l•n•o•p•••• •¥•§•¸•¹•º•»•¼•½•¾•¿•À•Â•Ã•Ç•È•Î•Ï•Ð•Ò•Ó•Ô•Õ•Û•Ü•ß•à•â•ä•æ•ê•í•î•ï•ñ•ò•ó•ô•ö•ø•ú•û–@–A–C–D–E–F–J–K–L–M–O–d–k–x–z–{–|–}–¢–µ–Å—T—m—r—t—z—~—‡—š—£—¦—Ê—Ñ—â—ã˜N˜b')
call AmbsearchAdd('I', 'ˆ¤ˆÈˆÊˆËˆÌˆÍˆÏˆÐˆÑˆÓˆÔˆÕˆ×ˆÙˆÚˆÛˆÜˆÝˆßˆáˆâˆãˆäˆæˆçˆêˆëˆíˆîˆðˆóˆõˆöˆ÷ˆøˆù‰@‰A‰B‰C‰c‰¹‰Æ‰úŠâŠôŠõ‹F‹U‹}‹ŒeŒ‰Œ™Œ¢Œ¾ŒÜs¡ÊŽsŽ…ŽŠŽœŽËjFˆ¨¶Îíò‘b‘§’r’v’’’˜’§’¸’É“{“‰“ü”@”Â”Ñ”Ú”Û•®•ø–Z–…–¢–½—B—E—v—Ç')
call AmbsearchAdd('J', 'ŽqŽ–Ž—Ž˜Ž™ŽšŽ›ŽœŽŽžŽŸŽ Ž¡Ž£Ž¥Ž¦Ž¨Ž©Ž«Ž²ŽÀŽÖŽ×ŽáŽâŽãŽòŽóŽõŽöŽ÷ŽùAZ[\]_`abcdemnpqyz{}€‚ƒ„…‡•–—˜™œãäæçèéêëìíîðòóôö÷øùJ_blmnqrsvw¬¶·’n’†’¼’è“‡“ñ“ú”@˜H')
call AmbsearchAdd('K', 'ˆÃˆÊˆÍˆÙˆßˆê‰A‰B‰_‰e‰z‰Œ‰˜‰ž‰©‰º‰»‰¼‰½‰¿‰À‰Á‰Â‰Ä‰Å‰Æ‰Ç‰È‰É‰Ê‰Ë‰Ì‰Í‰Î‰Ð‰Ò‰Ó‰Ô‰×‰Ø‰Ù‰Û‰Ý‰ß‰á‰æ‰ê‰î‰ï‰ð‰ñ‰ò‰ó‰õ‰ö‰÷‰ù‰ú‰û‰üŠBŠCŠDŠEŠFŠGŠJŠKŠLŠ_ŠdŠeŠgŠiŠjŠkŠlŠmŠnŠoŠpŠrŠsŠtŠuŠvŠ|ŠƒŠ„Š…Š‡ŠˆŠ‰ŠŠŠŒŠŠŽŠ”Š Š£Š¥Š¦Š§Š¨Š©ŠªŠ«Š¬Š®Š¯Š°Š±Š²Š³Š´ŠµŠ¶Š·Š¸Š»Š¼Š½Š¾Š¿ŠÂŠÃŠÄŠÅŠÇŠÈŠÉŠÊŠÌŠÍŠÏŠÑŠÒŠÓŠÔŠÕŠÖŠ×ŠÙŠÝŠçŠéŠëŠìŠíŠîŠïŠñŠòŠóŠôŠõŠöŠ÷ŠøŠùŠúŠûŠü‹@‹A‹C‹D‹F‹G‹I‹K‹L‹M‹N‹O‹P‹Q‹R‹S‹e‹g‹i‹l‹p‹q‹r‹u‹v‹x‹y‹z‹{‹|‹}‹~‹€‹‹ƒ‹…‹†‹‡‹‰‹Š‹‹‹Œ‹Ž‹‹‹‘‹’‹“‹•‹–‹—‹‹ž‹Ÿ‹£‹¤‹¥‹¦‹©‹«‹¬‹­‹°‹±‹²‹³‹´‹µ‹¶‹·‹¸‹¹‹º‹»‹½‹¾‹¿‹Á‹Â‹Ã‹Ç‹È‹É‹Î‹Ï‹Ò‹Õ‹Ö‹Ø‹Ù‹Û‹Ý‹Þ‹ß‹à‹ã‹å‹æ‹ê‹ì‹ó‹üŒ@ŒCŒJŒKŒMŒNŒOŒPŒWŒXŒYŒZŒ[Œ^Œ_Œ`ŒaŒbŒcŒeŒfŒgŒhŒiŒkŒnŒoŒpŒsŒuŒvŒxŒyŒ{Œ~Œ†Œ‡ŒˆŒ‰ŒŠŒ‹ŒŒŒŒŒ’Œ“Œ”Œ•Œ—Œ˜Œ™ŒšŒ›ŒœŒŸŒ Œ¢Œ£Œ¤Œ¦Œ§Œ¨Œ©ŒªŒ«Œ¬Œ­Œ¯Œ°Œ±ŒµŒ¾ŒÀŒÂŒÃŒÄŒÅŒÇŒÈŒÉŒÊŒËŒÌŒÍŒÎŒÖŒÙŒÚŒÛŒãŒêŒðŒòŒóŒõŒöŒ÷ŒøŒúŒûŒü@BDEFHIKLNPQRSTUXZ\]^`abcdegijklmqrstuvwxyz|~€‚„‡Ž‘’“•˜œž¡¢¤¥¦§©ª¬®°½Ó×ÛíŽEŽPŽ\ŽqŽuŽ†ŽŽŽ”Ž–Ž™ŽÔŽØŽÞŽêŽëŽñŽõŽ÷Lbd‘Ÿ¬ÁÅÈÚàãøüHOS_hs”´º¿ÎØì‘g‘q‘t‘‘ ‘¤‘Ì‘Ö‘Ý‘ã’J’S’b’f’z’…’›’¦’®’´’Ê“G“]“€““‚“š“ª“Ü“ï“ú”Z”z”ƒ”¯”Þ”ß”ä”ç”ì”í•K•X•|•…•—•¢•²•·•¿•Ä•Ç•Î•Ï•Ð•Ô•é•ö•ø•û–F–M–T–k–š–¶–Ñ–Õ–Ø–å–ò—q—v—ˆ—‹——˜—Æ—ï—ö˜a')
call AmbsearchAdd('M', '‰E‰v‰~‰º‰è‰ë‰ñŠFŠXŠwŠªŠ²ŠÅŠÏŠÔŠÛŠáŠî‹{‹‹–‹¹‹ÈŒQŒbŒ}Œ‹Œ©Œ³Œ¶Œ¹ŒÈŒÎŒðŒõŒü`av¬ÃÅÕŽOŽQŽSŽ|Ž‡Ž“ŽŽ¨Ž©ŽºŽÀŽÒŽáŽçŽü@Xu„”—Ÿ¡¢µ¼ÙöX\^fgm…ª­³·½ÌÝêö‘O‘S‘f‘r‘€‘‹‘‘·‘º‘Ò’Z’Ž’¬’¿“I“X“s“““¤“±“¹“ì“ï”C”F”R”n”ž”Ñ”ü•n•‰••‘•¨•´•¶•·•Ä•ê•ñ•ô–S–]–d–q–{–€––‚–ƒ–„–…–‡–ˆ–‹–Œ–”–•–––š–œ––ž–Ÿ–¡–¢–£–¦–§–¬–­–¯–°–±–²–³–µ–¶–¹–º–¼–½–¾–¿–À–Á–Â–Å–Æ–È–Ê–Í–Î–Ï–Ñ–Ò–Ó–Ô–Õ–Ø–Ù–Ú–ß–â–ä–å–æ—p——Ë—Î˜H˜R˜Z˜d˜f')
call AmbsearchAdd('N', 'ˆ¬ˆÔˆù‰i‰„‰”‰£‰¤‰¹‰½‰Ä‰×‰ùŠŠŠµŠÑŠè‹I‹U‹ƒ‹êŒZŒ{Œ›Œ¬Œãc§ªØÚŽcŽ—Ž™Ž¡ŽµŽÎŽÏŽáŽåKq—œ®¸ÀãæîLMQVln¬¶¼é‘R‘ž‘¥‘Ó‘Þ‘÷’E’Q’S’j’l’†’‡’­’·’¼’ë“T“h“o“z“{“Š““™“¦“¿“Ý“à“ê“ì“î“ï“ñ“ò“ó“÷“ú“û“ü”@”A”C”D”E”F”J”L”M”N”O”R”S”Y”Z”[”\”]”_”g”²”¼”Í•c•z•À•í–@–D–S–]–°–³–¼–Â–ì—¬—Õ—Ü—û˜a')
call AmbsearchAdd('O', '‰j‰˜‰š‰›‰œ‰‰ž‰Ÿ‰¡‰¢‰£‰¤‰¥‰©‰«‰­‰®‰¯‰³‰µ‰¶‰·‰¸‰¹‰ºŠTŠeŠoŠ×‹N‹S‹u‹y‹‹°‹³‹º‹»‹Á‹ð‹ñŒµŒÈŒãŒäŒöcs~÷ŽvŽ¡ŽåŽïŽûCIPd—¬Dbe„Š¶ÉÜî‘—‘¡‘½‘Ñ‘Ó‘å’j’u’x’·’Ç’í“{“¯”[”q”Æ”ö•\•v•‰•‹•¢•â–K–`–Ê–ô—Y—c—x—}—Ž—ò˜V˜a')
call AmbsearchAdd('P', '”g”j”Å•ª•½•Â–{')
call AmbsearchAdd('R', 'Šy‹™“™–ß–ö—…—‡—ˆ—Š—‹——Ž———‘—“—”———˜—™—š——Ÿ— —¢—£—¤—¥—¦—§—ª—¬—¯—°—±—²—³—¶—·—¸—¹—»—¼—¾—¿—Á—Â—Ã—Æ—Ç—Ê—Ë—Ì—Í—Î—Ï—Ð—Ñ—Õ—Ö—×—Û—Ü—Ý—Þ—ß—á—â—ã—ç—é—ê—ë—ì—í—î—ï—ð—ñ—ò—ó—ô—õ—ö—û˜A˜B˜F˜H˜I˜J˜L˜N˜O˜Q˜R˜V˜Y˜Z˜^˜_')
call AmbsearchAdd('S', 'ˆçˆó‰h‰s‰€‰ˆ‰Ž‰–‰º‰È‰ß‰îŠOŠoŠ„ŠŠŠ¦Š©ŠÖŠòŠù‹L‹s‹t‹z‹~‹Ž‹›‹Ÿ‹£‹©‹«‹­‹·‹Ø‹ó‹÷Œ’ŒåŒóDKUXi²´¶·¸»¼½ÀÂÃÄÅÈÉÊËÌÍÎÏÐÓÕÖ×ØÙÚÛàâçèìíïðôõö÷ûüŽ@ŽBŽCŽDŽEŽMŽOŽPŽQŽRŽSŽUŽVŽYŽZŽ\Ž^Ž_ŽdŽfŽgŽhŽiŽjŽkŽlŽmŽnŽoŽpŽqŽsŽtŽuŽvŽwŽxŽ{Ž|Ž}Ž~Ž€ŽŽƒŽ„Ž…Ž†Ž‡ŽˆŽ‰ŽŠŽ‹ŽŒŽŽŽŽŽŽ‘Ž’Ž“Ž”Ž•Ž˜ŽŸŽ Ž¦Ž©Ž®Ž¯ŽµŽ·Ž¸ŽºŽ¼Ž½Ž¾Ž¿ŽÅŽÉŽÊŽËŽÌŽÍŽÎŽÏŽÐŽÒŽÓŽÔŽÕŽØŽÙŽÚŽÝŽÞŽßŽâŽåŽæŽçŽèŽéŽêŽëŽìŽíŽïŽðŽñŽõŽöŽúŽûŽü@ABCDEGHIKLMOPTVWXZ]`adfhijklortu{ƒ‡ˆ‰Š‹Ž‘”•žŸ ¡¢¤¥§ª«¬­®°²³´µ¶¸º»¼ÀÁÂÄÅÆÇÈÉÊËÌÍÎÏÐÑÕ×ØÙÚÛÜàáãéîúüABDEFGHLMNOPQRSTUVXZ[\^_abdefghijk|‚ƒ„…†‡ˆŠ‹ŒŽ’”•˜™Ÿ¡¢£¤§¨©ª«¬­®¯°³´µ¶·¸¹º»¼½¾¿ÀÂÃÄÇÈÉËÌÍÎÏÐÑÓÔÕØÙÚÛÜÝÞßàáãåæçèéêìíîðòóôõöùü‘@‘D‘E‘H‘I‘J‘K‘L‘N‘S‘Y‘[‘a‘b‘c‘d‘e‘f‘g‘i‘j‘m‘n‘o‘q‘r‘s‘t‘w‘z‘{‘|‘}‘€‘‘‚‘ƒ‘…‘‡‘ˆ‘Š‘‹‘‘‘‘‘’‘”‘•‘–‘—‘˜‘š‘›‘¡‘£‘¤‘¥‘¦‘§‘©‘ª‘«‘¬‘²‘¶‘·‘¸‘¹‘º‘Þ‘ã‘ò’B’T’Y’m’ƒ’’ª’²’¼’¾’Á’å’è’ê’ñ’÷“H“Y“‡““§”E”p”t”w”’”—”›”½”ð”õ•i•~•Â•ä•ç–W–^–n–––¹–Î–î—@—D—U—[—l—¢—¦—Á—â—é—ô')
call AmbsearchAdd('T', 'ˆ×ˆá‰“‰Å‰ðŠmŠpŠxŠyŠÑŠÙŠ÷‹M‹P‹Y‹l‹…‹Ÿ‹¤‹­‹¸‹Ê‹Î‹Þ‹ßŒ_ŒgŒoŒpŒŒŒŽŒ’Œ•ŒšŒ¤Œ­Œ·ŒËŒÛŒÝFjk‚°ÈÌÎÙßìŽBŽUŽdŽgŽiŽ~ŽŽŽ’Ž›ŽžŽŸŽ¡Ž·Ž¿ŽæŽèŽíŽõAW\cdkrŠ•ž¥¬°ÆäíôHTdhlqs}‚†‹ŽŸ®³¾ÏÚàâçí‘U‘n‘¢‘©‘«‘±‘¸‘¼‘½‘¾‘Ì‘Î‘Ï‘Ñ‘Ò‘Ó‘Ô‘Ö‘×‘Ø‘Ù‘Ü‘Ý‘Þ‘ß‘à‘ã‘ä‘å‘ê‘ì‘î‘ð‘ñ‘ò‘ó‘õ’A’B’I’J’O’P’Q’S’T’W’Y’Z’[’_’a’b’c’e’f’l’m’n’p’r’s’t’u’v’x’z’{’|’~’€’’‚’ƒ’„’…’†’‡’ˆ’‰’Š’‹’Œ’’Ž’’’’“’˜’™’š’›’ ’¡’¢’£’¤’¥’¦’§’©’ª’¬’­’®’¯’°’²’´’µ’·’¸’¹’º’¼’½’¾’¿’À’Á’Â’Ã’Ä’Ç’É’Ê’Ë’Ð’Ø’Þ’à’á’â’ã’å’æ’ç’è’é’ê’ë’ì’í’ï’ñ’ö’÷’ø’ù’ü“@“E“G“H“I“J“K“N“O“P“R“S“T“V“W“X“Y“]“_“`“a“c“f“h“k“l“n“o“r“s“w“x“y“|“}“~“€““‚“ƒ“‡“‰“Š“‹“Œ““““’“”“–“—“™“š“›“œ““ž“¢“£“¤“¥“¦“§“©“ª“«“¬“¹“»“½“¾“¿“Á“Â“Ä“Ç“Ê“Ë“Í“Ô“Ø“û”N”[”|”‘”º”½”à”æ”ï”ò”ö•U•Y•q•t•x•ƒ••½•Â•Ö•×•Û•ß•å•ï•ò•ó–C–K–L–R–a–­–¯–±–Ê–Ò–â—B—F—n—ƒ—Š—‘—˜—§—¯—±—²—³—·—Í—×—Þ—á—â—ì˜A˜I')
call AmbsearchAdd('U', 'ˆÚ‰E‰F‰H‰J‰Q‰Y‰^‰_‰f‰Æ‰ÌŠCŠí‹Q‹^‹‹›‹±ŒhŒ‚Œã¦ŽYŽfŽ|ŽŽ¸Ž½ŽÊŽóDn‰³ãA¤¶¿è‘a‘i‘£‘Å’D“¢“®“¾“à”n”~”„”–”ü•‚–„—J—L—w— —í˜r')
call AmbsearchAdd('W', 'ˆ«‰H‰ä‰ðŠ„Š³‹Z‹ÆŒ´ÐŽ„ŽáÂÎ“n“¶”»”Ï•¦•ª•Ê–Y–È–ó—Ö˜a˜b˜d˜f˜g˜p˜r')
call AmbsearchAdd('Y', 'ˆÀˆËˆÏˆÕˆö‰E‰r‰˜‰¡‰®‰Å‰ÆŠÉŠìŠñ‹X‹`‹g‹x‹|‹–ŒcŒ‹ŒÄŒÌŒÙDKNs˜ŽRŽlŽwŽ~Ž«ŽÐŽã_hª°Ä÷Œ¢Àá‘P‘•‘×‘ã’J“z“’“Ç“î”j”s”ª•a•Ä–F–L–œ–²–é–ì–î–ï–ð–ñ–ò–ó–ô–ö–ù–û–ü—@—A—B—D—E—F—H—I—J—L—P—R—T—U—V—X—Y—Z—[—\—]—^—_—a—c—e—f—g—h—i—j—l—m—n—p—q—r—t—v—w—x—z—{—}—~——‚—ƒ—Ç˜a')
call AmbsearchAdd('Z', '‹lÀÏÜÝÞßàèŽGŽOŽbŽcÛ}‘¥Åàâã‘K‘O‘P‘Q‘R‘S‘T‘U‘œ‘‘ž‘Ÿ‘ ‘¡‘¢‘­‘®‘¯‘°‘±‘¶‘ò’Ã“¤“ª')
