" key_exchange.pl generate this file.  Don't edit.
if !exists('*AmbsearchAdd') | finish | endif
scriptencoding cp932
call AmbsearchAdd('A', 'ˆ¤ˆ«ˆ³ˆÀˆÃˆÄ‰J‰·‰¿‰ß‰ï‰üŠJŠÔŠë‹“‹óŒZŒŠŒ»ŒãŒëŒúz‡ÝŽoŽšŽÓŽåHW‹¤ºÍãVÂÔóô‘€‘ˆ‘Š‘«’g’l’˜’©“V“Œ“–“ª”M”ñ•\•¶•Ò•Ó•à–\–¡–¾–û—L—V—\—]—a—˜N')
call AmbsearchAdd('B', '‰H‰»‹´gâêl“ú”n”{”~”ƒ”„”Ž”’”ž”»”Â”Å”Ó”Ô”õ”ü•@•a•b•n•s••”•§•¨•ª•¶•·•½•Ä•Ê•Ó•Ö•×•Ù•Û•à•æ•é•ê–S–Y–\–]–_–f–h–q–‹–––œ–³–Í–Ø–Ú')
call AmbsearchAdd('C', '‹ßŒŒŽUŽ¡Ž¿dk¬ç’l’m’n’r’u’z’|’ƒ’…’†’‡’ˆ’‰’‹’Œ’’Ž’˜’™’š’›’ ’¡’£’©’ª’¬’°’²’·’¸’¹’¼’À“û•ƒ—Í')
call AmbsearchAdd('D', 'ŠÙo‘Å‘ã‘ä‘å‘æ‘è’B’c’f’g’i’j’k’í“`“c“d“w“x“y“­“®“¯“°“±“¶“¹“º“Å“Æ“Ç“à•t')
call AmbsearchAdd('E', 'ˆÕ‰c‰f‰h‰i‰j‰p‰q‰t‰v‰w‰~‰€‰„‰ˆ‰‰‰“‰–‰ï‰ñŠGŽ}dÎ‘I“¾–ð')
call AmbsearchAdd('F', 'ŠÈŒÃ~ÄŽD[ß‘D‘‘‘¾“J“~“ñ•M•s•t•v•w•x•z•{•ƒ•‰•—•›•œ•ž•Ÿ• •¡•§•ª•±•²•¶•à–h˜V')
call AmbsearchAdd('G', 'ˆÊ‰º‰Í‰ä‰æ‰è‰ê‰ðŠOŠQŠXŠwŠyŠzŠÛŠÝŠáŠâŠçŠèŠú‹Z‹^‹`‹c‹t‹{‹‹™‹›‹­‹½‹Æ‹É‹Ê‹â‹ïŒQŒRŒSŒ^Œ`Œ|Œ€ŒƒŒŽŒ Œ±Œ³Œ´ŒµŒ¸Œ¹Œ»Œ¾ŒÀŒÜŒßŒãŒêŒëŒìs†‡Ž™ãéº‘g‘¤•û–ˆ–Ø')
call AmbsearchAdd('H', 'ˆêˆø‰H‰^‰f‰h‰p‰Ê‰Î‰ÔŠDŠJŠOŠzŠ±Šø‹@‹v‹´ŒoŒvŒƒŒ´Œ¸ŒõL|œ¶×âŽnŽ•Ž¡Et‰Èjl}¯°¶‘‘–‘ª‘¬‘¼’‹’Œ’£’á’ö“Œ“”“™“­“Æ“ú“ü”g”h”j”o”q”s”w”x”z”Ž”’” ”¨”ª”­”»”¼”½”Â”Å”Æ”Ç”Ñ”Û”ß”á”ä”ç”é”ì”ï”ñ”ò•@•K•M•S•U•W•X•[•\•]•a•i•n• •§•º•½•À•Â•Ã•Ï•Ð•Ò•Ó•Ô•Û•à•â•æ•ê•ï•ñ•ó•ú•û–@–K–L–k–{–¢—m—r—t—z—~—¦—Ê—Ñ—â˜N˜b')
call AmbsearchAdd('I', 'ˆ¤ˆÈˆÊˆÍˆÏˆÓˆÕˆÙˆÚˆÝˆßˆâˆãˆæˆçˆêˆóˆõˆöˆøˆù‰@‰c‰¹‰ÆŠâ‹}‹Œ‰Œ¢Œ¾ŒÜs¡ŽsŽ…ŽŠŽËjF¨¶Îíò‘§’r’˜’¸’É“ü”Â”Ñ”Û–…–¢–½—E—v—Ç')
call AmbsearchAdd('J', 'ŽqŽ–Ž—Ž™ŽšŽ›ŽŽžŽŸŽ¡Ž¥Ž¦Ž¨Ž©Ž«ŽÀŽáŽãŽóŽöŽ÷AZ\]cdnpq€ƒ‡•—˜œãæéêíîðóö_blm¬¶·’n’†’¼’è“‡“ñ“ú˜H')
call AmbsearchAdd('K', 'ˆÃˆÊˆÍˆÙˆßˆê‰_‰ž‰©‰º‰»‰¼‰½‰¿‰Á‰Â‰Ä‰Æ‰È‰Ê‰Ì‰Í‰Î‰Ô‰×‰Û‰Ý‰ß‰æ‰ê‰ï‰ð‰ñ‰õ‰üŠBŠCŠDŠEŠGŠJŠKŠLŠeŠgŠiŠmŠoŠpŠtŠvŠ„ŠˆŠ”Š¦Š§ŠªŠ®Š¯Š±Š²Š´ŠµŠ¿ŠÅŠÇŠÈŠÏŠÔŠÖŠÙŠÝŠçŠëŠìŠíŠîŠñŠóŠöŠ÷ŠøŠú‹@‹A‹C‹D‹G‹I‹K‹L‹M‹N‹q‹v‹x‹z‹{‹|‹}‹~‹‹ƒ‹…‹†‹‰‹‹‹Œ‹Ž‹‹“‹–‹ž‹Ÿ‹£‹¤‹¦‹«‹­‹³‹´‹¹‹»‹½‹¾‹Ç‹È‹É‹Î‹Ï‹Ö‹Ø‹ß‹à‹ã‹å‹æ‹ê‹óŒNŒPŒWŒZŒ^Œ`ŒaŒhŒiŒnŒoŒvŒxŒyŒ‡ŒˆŒ‰ŒŠŒ‹ŒŒŒŒ’Œ”ŒšŒ›ŒŸŒ Œ¢Œ¤Œ¦Œ§Œ©Œ¯Œ±ŒµŒ¾ŒÀŒÂŒÃŒÄŒÅŒÈŒÉŒËŒÌŒÎŒãŒêŒðŒóŒõŒöŒ÷ŒøŒúŒûŒü@DFHKLNZ\`cgklqsuz|~‚‡‘’•œ¡¢ª¬×ÛŽEŽ\ŽqŽuŽ†ŽŽŽ”Ž–Ž™ŽÔŽØŽñŽ÷d‘Ÿ¬ÁÈãHS_”´ºÎØì‘g‘q‘t‘‘ ‘¤‘Ì‘Ý‘ã’J’S’f’z’…’›’Ê“G“]““š“ª“ï“ú”z”ƒ”ß”ä”ç”ì•K•X•—•²•·•Ä•Ï•Ð•Ô•é•û–k–Ñ–Ø–å–ò—v—ˆ—˜˜a')
call AmbsearchAdd('M', '‰E‰v‰~‰º‰è‰ñŠXŠwŠªŠ²ŠÅŠÏŠÔŠÛŠáŠî‹{‹‹–‹¹‹ÈŒQŒ‹Œ©Œ³Œ¹ŒÈŒÎŒðŒõŒü`¬ÅÕŽOŽQŽŽ¨Ž©ŽºŽÀŽÒŽáŽçŽü@”—Ÿµ¼öX\^gm…­³·½ÌÝê‘O‘S‘f‘€‘‹‘‘·‘º‘Ò’Z’Ž’¬“I“X“s“¤“±“¹“ì“ï”C”F”R”n”ž”Ñ”ü•n•‰••¨•¶•·•Ä•ê•ñ–S–]–q–{–…–‡–ˆ–‹–––œ–ž–¡–¢–§–¬–¯–±–²–³–¼–½–¾–¿–À–Â–È–Ê–Í–Ñ–Ø–Ú–â–å—p——Î˜H˜Z')
call AmbsearchAdd('N', 'ˆù‰i‰„‰¤‰¹‰½‰Ä‰×ŠµŠè‹I‹ƒ‹êŒZŒ›ŒãcªØŽcŽ—Ž™Ž¡ŽµŽáŽåKq—œãæîMVl¬¶¼é‘R‘¥‘Þ’S’j’l’†’‡’·’¼’ë“T“o“Š“™“¿“à“ì“ï“ñ“÷“ú“û“ü”C”F”M”N”O”R”[”\”]”_”g”¼•z•À–@–S–]–³–¼–Â–ì—¬—Õ—û˜a')
call AmbsearchAdd('O', '‰j‰›‰‰ž‰¡‰¤‰©‰­‰®‰¶‰·‰¹‰ºŠeŠo‹N‹‹³‹»ŒµŒÈŒãŒöcs~÷ŽvŽ¡ŽåŽûCId—¬Dbe„¶Ü‘—‘½‘Ñ‘å’j’u’·’Ç’í“¯”[”q”Æ•\•v•‰•â–K–Ê—c—Ž˜V˜a')
call AmbsearchAdd('P', '”g”j”Å•ª•½•Â–{')
call AmbsearchAdd('R', 'Šy‹™“™—ˆ—Ž——‘———˜—— —¢—¤—¥—¦—§—ª—¬—¯—·—¼—¿—Ç—Ê—Ì—Í—Î—Ñ—Õ—Ö—Þ—ß—á—â—ç—ð—ñ—û˜A˜H˜J˜N˜V˜Z˜^˜_')
call AmbsearchAdd('S', 'ˆçˆó‰h‰€‰ˆ‰–‰º‰È‰ßŠOŠoŠ„Š¦ŠÖ‹L‹t‹z‹~‹Ž‹›‹Ÿ‹£‹«‹­‹Ø‹óŒ’ŒóDK¶·¸»ÀÄÅÈËÌÏÐÕ×ØÙÛàâìðô÷ûüŽ@ŽDŽEŽMŽOŽQŽRŽUŽYŽZŽ\Ž^Ž_ŽdŽgŽiŽjŽlŽmŽnŽoŽpŽqŽsŽtŽuŽvŽwŽxŽ}Ž~Ž€ŽŽ„Ž…Ž†ŽŠŽ‹ŽŒŽŽŽŽŽ‘Ž”Ž•ŽŸŽ¦Ž©Ž®Ž¯ŽµŽ¸ŽºŽ¿ŽÉŽÊŽËŽÌŽÐŽÒŽÓŽÔŽØŽÚŽåŽæŽçŽèŽíŽðŽñŽöŽûŽü@ABCEHIKOTWZ]dhjkotƒ‡ˆ‰Š‹‘”•Ÿ¤¥«¬­³µº¼ÁÄÆÈÍÎØÛÜáãéîADEFHMSVX[\^_begij‚„…”¡¢§¨«¬­®¯°³´¶·¸¹º»¼½ÂÃÈÌÎÏÑÓÔØÚÜÝßàáãæçéêìíòóôõü‘D‘I‘K‘S‘c‘f‘g‘n‘q‘t‘w‘z‘€‘‘ƒ‘ˆ‘Š‘‹‘‘‘•‘–‘—‘¤‘¥‘§‘©‘ª‘«‘¬‘²‘¶‘·‘¸‘¹‘º‘Þ‘ã’B’T’Y’m’ƒ’’ª’²’¼’è’ê’ñ“‡“”w”’”½”õ•i•Â–––î—D—[—l—¢—¦—â')
call AmbsearchAdd('T', '‰“‰ðŠmŠpŠyŠÙŠ÷‹M‹…‹Ÿ‹¤‹­‹Ê‹Î‹ßŒoŒŒŒŽŒ’ŒšŒ¤ŒËFk‚ÈÌÙßìŽUŽdŽgŽiŽ~ŽŽŽ›ŽžŽŸŽ¡Ž¿ŽæŽèŽíAW\cdkŠ•¥¬ÆíHl}‚®³ÏÚàâçí‘n‘¢‘©‘«‘±‘¸‘¼‘½‘¾‘Ì‘Î‘Ñ‘Ò‘Ô‘Ý‘Þ‘à‘ã‘ä‘å‘î’B’J’P’S’T’Y’Z’a’c’f’l’m’n’r’u’z’|’ƒ’…’†’‡’ˆ’‰’‹’Œ’’Ž’˜’™’š’›’ ’¡’£’©’ª’¬’°’²’·’¸’¹’¼’À’Ç’É’Ê’á’â’è’ê’ë’í’ñ’ö“G“I“J“K“S“T“V“W“X“]“_“`“c“k“o“s“w“x“y“}“~““‡“Š“Œ“’“”“–“™“š“œ““¢“¤“ª“¹“¾“¿“Á“Ç“Í“û”N”[”½”ï”ò•U•t•x•ƒ••½•Â•Ö•×•Û•ï•ó–K–L–¯–±–Ê–â—F—‘—˜—§—¯—·—Í—Þ—á—â˜A')
call AmbsearchAdd('U', 'ˆÚ‰E‰F‰H‰J‰^‰_‰f‰Æ‰ÌŠCŠí‹^‹‹›ŒhŒãŽYŽŽ¸ŽÊŽón‰³ãA¶‘Å“¢“®“¾“à”n”~”„”ü—L— ')
call AmbsearchAdd('W', 'ˆ«‰H‰ä‰ðŠ„‹Z‹ÆŒ´ÐŽ„ŽáÎ“¶”»•ª•Ê–Y–È–ó—Ö˜a˜b')
call AmbsearchAdd('Y', 'ˆÀˆÏˆÕˆö‰E‰¡‰®‰ÆŠìŠñ‹`‹x‹|‹–Œ‹ŒÄŒÌDKNsŽRŽlŽwŽ~Ž«ŽÐŽãhÄ¢á‘P‘•‘ã’J“’“Ç”j”s”ª•a•Ä–L–œ–²–é–ì–î–ð–ñ–ò–ó–û—A—D—E—F—L—R—V—X—[—\—]—a—c—e—j—l—m—p—r—t—v—z—{—~——‚—Ç˜a')
call AmbsearchAdd('Z', 'ÀÏÝÞßàŽGŽOŽcÛ}Åàâã‘K‘O‘P‘R‘S‘œ‘‘Ÿ‘ ‘¢‘®‘°‘±‘¶“¤“ª')
